spring:
  rabbitmq:
    host: 192.168.121.129
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        #消息自动确认
        acknowledge-mode: auto